---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  namespace: prod
  labels:
    app: simple-api
spec:
  selector:
    matchLabels:
      app: simple-api
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: ap-osaka-1.ocir.io/axopk4dsgaw5/simple-api
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "curl -X POST http://localhost:8080/actuator/shutdown",
                  ]
          env:
            - name: TZ
              value: Asia/Tokyo
      imagePullSecrets:
        - name: ocicred
      terminationGracePeriodSeconds: 30
